namespace SboxAgentBridge.Editor;

internal static class CommandDispatcher
{
	public static BridgeResponse Dispatch( BridgeRequest request )
	{
		return request.Action switch
		{
			"bridge.status" => EditorHandlers.Status( request ),
			"editor.context" => EditorHandlers.Context( request ),
			"editor.tabs" => EditorHandlers.Tabs( request ),
			"editor.activate_tab" => EditorHandlers.ActivateTab( request ),
			"editor.open_scene" => EditorHandlers.OpenScene( request ),
			"editor.get_selection" => EditorHandlers.GetSelection( request ),
			"editor.set_selection" => EditorHandlers.SetSelection( request ),
			"editor.save_scene" => EditorHandlers.SaveScene( request ),
			"editor.undo" => EditorHandlers.Undo( request ),
			"editor.redo" => EditorHandlers.Redo( request ),
			"editor.frame_object" => EditorHandlers.FrameObject( request ),
			"editor.play_state" => EditorHandlers.PlayState( request ),
			"editor.play" => EditorHandlers.Play( request ),
			"editor.stop" => EditorHandlers.Stop( request ),
			"editor.logs" => EditorHandlers.Logs( request ),
			"editor.compile_status" => EditorHandlers.CompileStatus( request ),
			"editor.feedback" => EditorHandlers.Feedback( request ),
			"script.create" => ScriptHandlers.Create( request ),
			"script.edit" => ScriptHandlers.Edit( request ),
			"script.delete" => ScriptHandlers.Delete( request ),
			"asset.search" => AssetHandlers.Search( request ),
			"asset.get_info" => AssetHandlers.GetInfo( request ),
			"asset.inspect_model" => AssetHandlers.InspectModel( request ),
			"asset.get_orientation_override" => AssetHandlers.GetOrientationOverride( request ),
			"asset.set_orientation_override" => AssetHandlers.SetOrientationOverride( request ),
			"asset.assign_model" => AssetHandlers.AssignModel( request ),
			"asset.assign_material" => AssetHandlers.AssignMaterial( request ),
			"asset.create_material" => AssetHandlers.CreateMaterial( request ),
			"asset.set_material_property" => AssetHandlers.SetMaterialProperty( request ),
			"visual.capture_camera" => VisualHandlers.CaptureCamera( request ),
			"sound.list" => SoundHandlers.List( request ),
			"sound.get_info" => SoundHandlers.GetInfo( request ),
			"sound.create_event" => SoundHandlers.CreateEvent( request ),
			"sound.assign" => SoundHandlers.Assign( request ),
			"sound.preview" => SoundHandlers.Preview( request ),
			"physics.add_physics" => PhysicsHandlers.AddPhysics( request ),
			"physics.add_collider" => PhysicsHandlers.AddCollider( request ),
			"physics.add_joint" => PhysicsHandlers.AddJoint( request ),
			"physics.raycast" => PhysicsHandlers.Raycast( request ),
			"prefab.create" => PrefabHandlers.Create( request ),
			"prefab.list" => PrefabHandlers.List( request ),
			"prefab.get_info" => PrefabHandlers.GetInfo( request ),
			"prefab.instantiate" => PrefabHandlers.Instantiate( request ),
			"scene.summary" => SceneHandlers.Summary( request ),
			"scene.hierarchy" => SceneHandlers.Hierarchy( request ),
			"scene.find" => SceneHandlers.Find( request ),
			"scene.details" => SceneHandlers.Details( request ),
			"scene.batch" => SceneHandlers.Batch( request ),
			"gameobject.get" => GameObjectHandlers.Get( request ),
			"gameobject.create" => GameObjectHandlers.Create( request ),
			"gameobject.rename" => GameObjectHandlers.Rename( request ),
			"gameobject.set_transform" => GameObjectHandlers.SetTransform( request ),
			"gameobject.set_enabled" => GameObjectHandlers.SetEnabled( request ),
			"gameobject.destroy" => GameObjectHandlers.Destroy( request ),
			"gameobject.duplicate" => GameObjectHandlers.Duplicate( request ),
			"gameobject.reparent" => GameObjectHandlers.Reparent( request ),
			"gameobject.place_asset" => GameObjectHandlers.PlaceAsset( request ),
			"component.list_types" => ComponentHandlers.ListTypes( request ),
			"component.list_on_gameobject" => ComponentHandlers.ListOnGameObject( request ),
			"component.get" => ComponentHandlers.Get( request ),
			"component.get_properties" => ComponentHandlers.GetProperties( request ),
			"component.add" => ComponentHandlers.Add( request ),
			"component.remove" => ComponentHandlers.Remove( request ),
			"component.set_enabled" => ComponentHandlers.SetEnabled( request ),
			"component.set_property" => ComponentHandlers.SetProperty( request ),
			"component.validate_property" => ComponentHandlers.ValidateProperty( request ),
			_ => BridgeResponse.Fail(
				request.Id,
				$"Unknown bridge action '{request.Action}'",
				"Use one of: bridge.status, editor.context, editor.tabs, editor.activate_tab, editor.open_scene, editor.get_selection, editor.set_selection, editor.save_scene, editor.undo, editor.redo, editor.frame_object, editor.play_state, editor.play, editor.stop, editor.logs, editor.compile_status, editor.feedback, script.create, script.edit, script.delete, asset.search, asset.get_info, asset.inspect_model, asset.get_orientation_override, asset.set_orientation_override, asset.assign_model, asset.assign_material, asset.create_material, asset.set_material_property, visual.capture_camera, sound.list, sound.get_info, sound.create_event, sound.assign, sound.preview, physics.add_physics, physics.add_collider, physics.add_joint, physics.raycast, prefab.create, prefab.list, prefab.get_info, prefab.instantiate, scene.summary, scene.hierarchy, scene.find, scene.details, scene.batch, gameobject.get, gameobject.create, gameobject.rename, gameobject.set_transform, gameobject.set_enabled, gameobject.destroy, gameobject.duplicate, gameobject.reparent, gameobject.place_asset, component.list_types, component.list_on_gameobject, component.get, component.get_properties, component.add, component.remove, component.set_enabled, component.set_property, component.validate_property."
			)
		};
	}
}
